---
title: "Data Cleaning"
author: "Xue Zhang"
date: "2023-12-01"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(gtsummary)
library(ggridges)
```

```{r}
score_df = 
  read_csv("./data/project_1_data.csv") |>
  janitor::clean_names()
```

```{r}
# Check for missing data
colSums(is.na(score_df))
```

```{r}
# Convert character to factor for regression analysis
score_df_6 = score_df |>
  mutate(
    gender = as.factor(gender),
    ethnic_group = as.factor(ethnic_group),
    parent_educ = as.factor(parent_educ),
    lunch_type = as.factor(lunch_type),
    test_prep = as.factor(test_prep),
    parent_marital_status = as.factor(parent_marital_status),
    practice_sport = as.factor(practice_sport),
    is_first_child = as.factor(is_first_child),
    transport_means = as.factor(transport_means),
    wkly_study_hours = as.factor(wkly_study_hours)
  )
```

```{r}
# Checking proportion of missing data for each variable
prop_missing_each_column = colSums(is.na(score_df_6)) / nrow(score_df_6)

barplot(prop_missing_each_column, 
        main="Proportion of Missing Data by Column", 
        xlab="Columns",
        ylab="Proportion")
```

```{r}
# Impute missing values with the mode (the most frequently occurring category) or categorical variables

# Function to compute mode
compute_mode = function(x) {
  tbl = table(na.omit(x))
  as.character(names(tbl)[which.max(tbl)])
}

# Applying mode imputation to a specific column
score_df_6 = score_df_6 |>
  mutate(ethnic_group = ifelse(is.na(ethnic_group), compute_mode(ethnic_group), ethnic_group))

# Repeat for other categorical variables
score_df_6 = score_df_6 |>
  mutate(parent_educ = ifelse(is.na(parent_educ), compute_mode(parent_educ), parent_educ))
```

```{r}
# Histogram
hist(score_df_6$nr_siblings, 
     main="Histogram of nr_siblings", 
     xlab="nr_siblings")

# QQ Plot
qqnorm(score_df_6$nr_siblings)
qqline(score_df_6$nr_siblings, col="red")
```

**The histogram showed a right-skewed curve.**


```{r, include = FALSE}
# Shapiro-Wilk Test
shapiro.test(score_df_6$nr_siblings)
```

**The p-value is less than 0.05, which indicates non-normality.**

```{r}
# Median imputation for `nr_sibling`
median_siblings =  median(score_df_6$nr_siblings, na.rm = TRUE)
score_df_6$nr_siblings[is.na(score_df_6$nr_siblings)] = median_siblings
```


```{r}
# The proportion of missing data for `practice_sport` is small (`16`), choose to remove those records.

# `complete.cases() is used to find rows that have no missing values in the `practice_sport` column
score_df_6 = score_df_6 |>
  filter(complete.cases(practice_sport)) 
```

