---
title: "p8130_final_project"
date: "2023-11-28"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(gtsummary)
library(ggridges)
```

```{r}
score_df = 
  read_csv("./data/project_1_data.csv") |>
  janitor::clean_names()
```







```{r}
proj1=score_df
proj1 %>%
tbl_summary(
  missing_text = "(Missing)", # counts missing values
  statistic = list(all_continuous() ~ "mean={mean} (min={min}, max={max}, sd={sd})",
                   all_categorical() ~ "n={n} (p={p}%)") # stats for categorical
 # specify variables to include
  ) %>%
bold_labels()  %>%
italicize_levels()
```




#Figure 1
```{R}

long_data <- pivot_longer(proj1, 
                          cols = c("reading_score", "writing_score", "math_score"), 
                          names_to = "Exam", 
                          values_to = "Score")
bounds <- long_data %>%
  group_by(Exam) %>%
  summarize(Q1 = quantile(Score, probs = 0.25),
            Q3 = quantile(Score, probs = 0.75)) %>%
  mutate(IQR = Q3 - Q1,
         LowerBound = Q1 - 1.5 * IQR,
         UpperBound = Q3 + 1.5 * IQR) %>%
  ungroup()

# Add a column to the original data indicating outliers
long_data <- long_data %>%
  left_join(bounds, by = "Exam") %>%
  mutate(Outlier = ifelse(Score < LowerBound | Score > UpperBound, TRUE, FALSE))

# Create the ridgeline plot
ggplot(long_data) +
  geom_density_ridges(aes(x = Score, y = Exam, fill = Exam)) +
  geom_point(data = filter(long_data, Outlier), aes(x = Score, y = Exam, color = Exam), size = 2, shape = 21, show.legend = FALSE) +
  scale_fill_viridis_d() + # Adds a nice color scale; change as needed
  labs(title = 'Distribution of Scores by Exam with Outliers', x = 'Score', y = 'Exam') +
  theme_ridges() # Theme for ridgeline plots
```





```{r, include = FALSE}
# Check for missing data
colSums(is.na(score_df))
```

```{r, include = FALSE}
# Convert character to factor for regression analysis
score_df = score_df |>
  mutate(
    gender = as.factor(gender),
    ethnic_group = as.factor(ethnic_group),
    parent_educ = as.factor(parent_educ),
    lunch_type = as.factor(lunch_type),
    test_prep = as.factor(test_prep),
    parent_marital_status = as.factor(parent_marital_status),
    practice_sport = as.factor(practice_sport),
    is_first_child = as.factor(is_first_child),
    transport_means = as.factor(transport_means),
    wkly_study_hours = as.factor(wkly_study_hours)
  )
```

```{r, include = FALSE}
# Checking proportion of missing data for each variable
prop_missing_each_column = colSums(is.na(score_df)) / nrow(score_df)

prop_missing_total = sum(is.na(score_df)) / prod(dim(score_df))

barplot(prop_missing_each_column, main="Proportion of Missing Data by Column", 
        ylab="Proportion", xlab="Columns", las=2)
```

```{r, include = FALSE}
# Impute missing values with the mode (the most frequently occurring category) or categorical variables

# Function to compute mode
compute_mode = function(x) {
  tbl = table(na.omit(x))
  as.character(names(tbl)[which.max(tbl)])
}

# Applying mode imputation to a specific column
score_df = score_df |>
  mutate(ethnic_group = ifelse(is.na(ethnic_group), compute_mode(ethnic_group), ethnic_group))

# Repeat for other categorical variables
score_df = score_df |>
  mutate(parent_educ = ifelse(is.na(parent_educ), compute_mode(parent_educ), parent_educ))
```

```{r, include = FALSE}
# Histogram
hist(score_df$nr_siblings, main="Histogram of nr_siblings", xlab="nr_siblings")

# QQ Plot
qqnorm(score_df$nr_siblings)
qqline(score_df$nr_siblings, col="red")
```

**The histogram showed a right-skewed curve.**


```{r, include = FALSE}
# Shapiro-Wilk Test
shapiro.test(score_df$nr_siblings)
```

**The p-value is less than 0.05, which indicates non-normality.**

```{r, include = FALSE}
# Median imputation for `nr_sibling`
median_siblings =  median(score_df$nr_siblings, na.rm = TRUE)
score_df$nr_siblings[is.na(score_df$nr_siblings)] = median_siblings
```


```{r, include = FALSE}
# The proportion of missing data for `practice_sport` is small (`16`), choose to remove those records.

# `complete.cases() is used to find rows that have no missing values in the `practice_sport` column
score_df = score_df |>
  filter(complete.cases(practice_sport)) 
```

